name: C Basics Test and Build Utility

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Check out the repository

      - name: test
        run: make ctest
        ./test_script > test_results.txt
        gcov ctest-main.c > main_coverage.txt
        gcov ctest-convert.c > convert_coverage.txt 
      
      - name: upload test results
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ./test_results.txt

      - name: upload main coverage report # Subtask name
        uses: actions/upload-artifact@v4  # This is an upload task
        with:
          name: Test Main Coverage Report  # Artifact name
          path: ./main_coverage.txt  # Path to the test results file
      
      - name: upload convert coverage report # Subtask name
        uses: actions/upload-artifact@v4  # This is an upload task
        with:
          name: Conver coverage report  # Artifact name
          path: ./convert_coverage.txt  # Path to the test results file
