name: C Basics Test and Build Utility

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile ctest with coverage
        run: make ctest

      - name: Run tests and collect coverage
        run: |
          ./test_script > test_results.txt
          gcov ctest-main.c -o . > main_coverage.txt
          gcov ctest-convert.c -o . > convert_coverage.txt
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ./test_results.txt

      - name: Upload main coverage report
        uses: actions/upload-artifact@v4
        with:
          name: Main Coverage Report
          path: ./main_coverage.txt
      
      - name: Upload convert coverage report
        uses: actions/upload-artifact@v4
        with:
          name: Convert Coverage Report
          path: ./convert_coverage.txt
